const List = [
  {
    id: 1,
    title: "안녕하세요 감사해요 잘있어요 다시만나요",
    content: "게시물 내용",
    createdAt: "2023/06/23",
    viewcount_id: 15,
    writer: "홍당무",
  },
  {
    id: 2,
    title: "반갑습니다",
    content: "게시물 내용2",
    createdAt: "2023/06/24",
    viewcount_id: 1124,
    writer: "홍두깨",
  },
  {
    id: 3,
    title: "잘가세요",
    content: "게시물 내용3",
    createdAt: "2023/06/25",
    viewcount_id: 12,
    writer: "홍차",
  },
  {
    id: 4,
    title: "안녕하세요",
    content: "게시물 내용",
    createdAt: "2023/06/23",
    viewcount_id: 15,
    writer: "홍당무",
  },
  {
    id: 5,
    title: "안녕하세요",
    content: "게시물 내용",
    createdAt: "2023/06/23",
    viewcount_id: 15,
    writer: "홍당무",
  },
  {
    id: 6,
    title: "안녕하세요",
    content: "게시물 내용",
    createdAt: "2023/06/23",
    viewcount_id: 15,
    writer: "홍당무",
  },
  {
    id: 7,
    title: "안녕하세요",
    content: "게시물 내용",
    createdAt: "2023/06/23",
    viewcount_id: 15,
    writer: "홍당무",
  },
  {
    id: 8,
    title: "안녕하세요",
    content: "게시물 내용",
    createdAt: "2023/06/23",
    viewcount_id: 15,
    writer: "홍당무",
  },
  {
    id: 9,
    title: "안녕하세요",
    content: "게시물 내용",
    createdAt: "2023/06/23",
    viewcount_id: 15,
    writer: "홍당무",
  },
  {
    id: 10,
    title: "안녕하세요",
    content: "게시물 내용",
    createdAt: "2023/06/23",
    viewcount_id: 15,
    writer: "홍당무",
  },
];
export default List;
